"""Add GLiNER counterparty columns

Revision ID: 00d93c533932
Revises: a998b3a25d31
Create Date: 2026-10-06 13:27:37.413434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00d93c533932'
down_revision: Union[str, Sequence[str], None] = 'a998b3a25d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('counterparty_name', sa.String(length=255), nullable=True))
    op.add_column('bank_transactions', sa.Column('counterparty_type', sa.String(length=50), nullable=True))
    op.add_column('bank_transactions', sa.Column('counterparty_identifier', sa.String(length=255), nullable=True))
    op.add_column('bank_transactions', sa.Column('counterparty_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('bank_transactions', sa.Column('counterparty_source', sa.String(length=50), nullable=True))
    op.add_column('bank_transactions', sa.Column('counterparty_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transactions', 'counterparty_status')
    op.drop_column('bank_transactions', 'counterparty_source')
    op.drop_column('bank_transactions', 'counterparty_confidence')
    op.drop_column('bank_transactions', 'counterparty_identifier')
    op.drop_column('bank_transactions', 'counterparty_type')
    op.drop_column('bank_transactions', 'counterparty_name')
    # ### end Alembic commands ###

