"""create_user_permissions_table

Revision ID: 05fd6fbbe345
Revises: 4d833242b8fa
Create Date: 2026-09-30 13:19:01.648142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fd6fbbe345'
down_revision: Union[str, Sequence[str], None] = '4d833242b8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_create_case', sa.Boolean(), nullable=False),
    sa.Column('can_upload_files', sa.Boolean(), nullable=False),
    sa.Column('can_update_files', sa.Boolean(), nullable=False),
    sa.Column('can_delete_files', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=True)
    # Populate existing users with full default permissions
    op.execute(
        """
        INSERT INTO user_permissions (user_id, can_create_case, can_upload_files, can_update_files, can_delete_files)
        SELECT id, true, true, true, true FROM users
        ON CONFLICT (user_id) DO NOTHING;
        """
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
