"""rollback_bank_statement_update_bank_transactions

Revision ID: 392e2b338fad
Revises: 93678aa8d063
Create Date: 2026-09-30 13:37:10.348325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '392e2b338fad'
down_revision: Union[str, Sequence[str], None] = '93678aa8d063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_statement_case_id'), table_name='bank_statement')
    op.drop_index(op.f('ix_bank_statement_file_id'), table_name='bank_statement')
    op.drop_index(op.f('ix_bank_statement_id'), table_name='bank_statement')
    op.drop_index(op.f('ix_bank_statement_transaction_date'), table_name='bank_statement')
    op.drop_table('bank_statement')
    op.add_column('bank_transactions', sa.Column('mode', sa.Text(), nullable=True))
    op.drop_column('bank_transactions', 'raw_row')
    op.drop_column('bank_transactions', 'reference_number')
    op.drop_column('bank_transactions', 'source_row')
    op.drop_column('bank_transactions', 'source_page')
    op.drop_column('bank_transactions', 'raw_narration')
    op.drop_column('bank_transactions', 'extraction_confidence')
    op.drop_column('bank_transactions', 'alpha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('alpha', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bank_transactions', sa.Column('extraction_confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True))
    op.add_column('bank_transactions', sa.Column('raw_narration', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bank_transactions', sa.Column('source_page', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bank_transactions', sa.Column('source_row', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bank_transactions', sa.Column('reference_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bank_transactions', sa.Column('raw_row', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('bank_transactions', 'mode')
    op.create_table('bank_statement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cheque_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('debit', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('credit', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('mode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('bank_statement_case_id_fkey')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('bank_statement_file_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_statement_pkey'))
    )
    op.create_index(op.f('ix_bank_statement_transaction_date'), 'bank_statement', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_statement_id'), 'bank_statement', ['id'], unique=False)
    op.create_index(op.f('ix_bank_statement_file_id'), 'bank_statement', ['file_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_case_id'), 'bank_statement', ['case_id'], unique=False)
    # ### end Alembic commands ###
