"""create_bank_statement_table

Revision ID: 93678aa8d063
Revises: ae558b42c39f
Create Date: 2026-09-30 12:22:37.101658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93678aa8d063'
down_revision: Union[str, Sequence[str], None] = 'ae558b42c39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cheque_number', sa.Text(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statement_case_id'), 'bank_statement', ['case_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_file_id'), 'bank_statement', ['file_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_id'), 'bank_statement', ['id'], unique=False)
    op.create_index(op.f('ix_bank_statement_transaction_date'), 'bank_statement', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_statement_transaction_date'), table_name='bank_statement')
    op.drop_index(op.f('ix_bank_statement_id'), table_name='bank_statement')
    op.drop_index(op.f('ix_bank_statement_file_id'), table_name='bank_statement')
    op.drop_index(op.f('ix_bank_statement_case_id'), table_name='bank_statement')
    op.drop_table('bank_statement')
    # ### end Alembic commands ###
