"""add raw_excel_path to files

Revision ID: 9ce6eb4c679c
Revises: 05e0b0565083
Create Date: 2026-09-29 15:04:35.680710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce6eb4c679c'
down_revision: Union[str, Sequence[str], None] = '05e0b0565083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('raw_excel_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'raw_excel_path')
    # ### end Alembic commands ###
