"""create statement format mappings table

Revision ID: 9d58368e8240
Revises: 3428f591828f
Create Date: 2026-09-24 00:29:38.167408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d58368e8240'
down_revision: Union[str, Sequence[str], None] = '3428f591828f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_format_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('format_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('mapping_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('mapping_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_format_mappings_format_fingerprint'), 'statement_format_mappings', ['format_fingerprint'], unique=True)
    op.create_index(op.f('ix_statement_format_mappings_id'), 'statement_format_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_format_mappings_id'), table_name='statement_format_mappings')
    op.drop_index(op.f('ix_statement_format_mappings_format_fingerprint'), table_name='statement_format_mappings')
    op.drop_table('statement_format_mappings')
    # ### end Alembic commands ###
