"""Add transaction_mode table

Revision ID: a998b3a25d31
Revises: efa9b4b1eb01
Create Date: 2026-10-01 12:24:47.620417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a998b3a25d31'
down_revision: Union[str, Sequence[str], None] = 'efa9b4b1eb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_mode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_mode_id'), 'transaction_mode', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_mode_mode'), 'transaction_mode', ['mode'], unique=True)
    
    # Seed initial data
    transaction_mode_table = sa.table(
        'transaction_mode',
        sa.column('mode', sa.String(length=100))
    )
    op.bulk_insert(
        transaction_mode_table,
        [
            {'mode': 'UPI'},
            {'mode': 'NEFT'},
            {'mode': 'RTGS'},
            {'mode': 'IMPS'},
            {'mode': 'ATM'},
            {'mode': 'CASH'},
            {'mode': 'CHEQUE'},
            {'mode': 'POS'},
            {'mode': 'NACH'},
            {'mode': 'ECS'}
        ]
    )
    
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_mode_mode'), table_name='transaction_mode')
    op.drop_index(op.f('ix_transaction_mode_id'), table_name='transaction_mode')
    op.drop_table('transaction_mode')
    # ### end Alembic commands ###
