"""add processing_stage and progress to files

Revision ID: ae558b42c39f
Revises: 9ce6eb4c679c
Create Date: 2026-09-29 15:22:20.039352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae558b42c39f'
down_revision: Union[str, Sequence[str], None] = '9ce6eb4c679c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('processing_stage', sa.String(length=100), nullable=True))
    op.add_column('files', sa.Column('processing_progress', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'processing_progress')
    op.drop_column('files', 'processing_stage')
    # ### end Alembic commands ###
