"""create bank transactions table

Revision ID: d92617a5a9f7
Revises: 9d58368e8240
Create Date: 2026-09-24 01:48:09.702713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92617a5a9f7'
down_revision: Union[str, Sequence[str], None] = '9d58368e8240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cheque_number', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.Text(), nullable=True),
    sa.Column('alpha', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_narration', sa.Text(), nullable=True),
    sa.Column('raw_row', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_case_id'), 'bank_transactions', ['case_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_file_id'), 'bank_transactions', ['file_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_file_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_case_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
