"""add account metadata to files and bank transactions

Revision ID: efa9b4b1eb01
Revises: 392e2b338fad
Create Date: 2026-09-30 17:48:00.722088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa9b4b1eb01'
down_revision: Union[str, Sequence[str], None] = '392e2b338fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('account_name', sa.String(length=255), nullable=True))
    op.add_column('bank_transactions', sa.Column('account_number', sa.String(length=100), nullable=True))
    op.add_column('files', sa.Column('account_name', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('account_number', sa.String(length=100), nullable=True))
    op.add_column('files', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('branch_name', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('ifsc', sa.String(length=50), nullable=True))
    op.add_column('files', sa.Column('micr', sa.String(length=50), nullable=True))
    op.add_column('files', sa.Column('account_type', sa.String(length=100), nullable=True))
    op.add_column('files', sa.Column('statement_start_date', sa.Date(), nullable=True))
    op.add_column('files', sa.Column('statement_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'statement_end_date')
    op.drop_column('files', 'statement_start_date')
    op.drop_column('files', 'account_type')
    op.drop_column('files', 'micr')
    op.drop_column('files', 'ifsc')
    op.drop_column('files', 'branch_name')
    op.drop_column('files', 'bank_name')
    op.drop_column('files', 'account_number')
    op.drop_column('files', 'account_name')
    op.drop_column('bank_transactions', 'account_number')
    op.drop_column('bank_transactions', 'account_name')
    # ### end Alembic commands ###
